server:
  port: 8783
  http2:
    enabled: true
info:
  tags:
    app: district
eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /swagger-ui.html
    metadata-map:
      zone: ${info.tags.app}
      startup: ${random.int}
  client:
    enabled: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
#请求处理的超时时间
ribbon.ReadTimeout: 60000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000
hystrix:
  threadpool:
    default:
      maximumSize: 1000
      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: 500
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 60000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 300
spring:
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/district?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: null
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      filters: stat
#      maxActive: 20
#      initialSize: 5
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 50
#      connection-init-sqls: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
#      stat-view-servlet:
#        login-username: device
#        login-password: 123457
#        allow: 127.0.0.1
#      remove-abandoned: true
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      naming:
#        implicit-strategy: com.hongmei.cehs.biz.common.config.MyImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        generate_statistics: true
        jdbc.batch_size: 100
        formate-sql: true
#  cache:
#    type: redis
#    redis:
#      time-to-live: 10d
#      use-key-prefix: true
#      key-prefix: cehs-
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  redis:
#    host: localhost
#    password:
#    timeout: PT3600S
#    database: 3
#  profiles:
#    active: @build.profile.id@
logging:
  level:
    root: warn
    com.hongmei: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS